apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platformstacks.platformstack.kubeplus
spec:
  group: platformstack.kubeplus
  version: v1alpha1
  names:
    kind: PlatformStack
    plural: platformstacks
  scope: Namespaced
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubeplus-platformoperator
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: platform-operator
  template:
    metadata:
      labels:
        app: platform-operator
    spec:
      containers:
      - name: platform-operator
        image: lmecld/platform-operator:0.0.3
        imagePullPolicy: Always
        command: [ "/platform-operator"]

